### ISSUE TITLE
IPA charts

### ISSUE THREAD

**Issue by xrotwang** [clld/lsi#3]
As a test for the IPA charts created via `pyclts`, I've integrated them here. E.g. https://lsi.clld.org/languages/BASHGALI#tipa
Let me know what you think.

**Comment by LinguList** [comment]
This is very nice, @xrotwang! I do not see by now if we need anything more. We can discuss the internal ordering of elements, such as `kʲ k` or of the vowels, to have the less complex elements in front, but it is basically all we need, and I think this will make a great impression for linguists in all lexical database which provide segmentated data mapped to clts.

BTW: @PhyloStar, you can nicely see that there's an inconsistency with `dʑ`, which should probably be `dʒ`.

**Comment by PhyloStar** [comment]
@xrotwang Wow! They look super cool. 

@LinguList Yes. I will look into this. Thank you.

**Comment by PhyloStar** [comment]
How can I update the clld app to point to the latest cldf here: https://github.com/lexibank/lsi/tree/master/cldf ?

**Comment by xrotwang** [comment]
You can't. Reloading the data and pushing the new database to the server
must be done by me.

Taraka Rama <notifications@github.com> schrieb am Fr., 4. Sep. 2020, 07:52:

**Comment by LinguList** [comment]
@PhyloStar, since @xrotwang is in holiday (and I'll be in holiday next
week), and since we need some more planning with respect to the app, let
us not rush this now. But as I wrote in an email, the clld integration
works extremely well, so this can be turned into a very nice application
later.

**Comment by PhyloStar** [comment]
Ok. Great. We can plan better.

Best,
Taraka
