### ISSUE TITLE
Integrate scanned book

### ISSUE THREAD

**Issue by xrotwang** [clld/lsi#4]
The scanned book is available at https://dsal.uchicago.edu/books/lsi/

The page numbers given in the [concept list](https://github.com/concepticon/concepticon-data/blob/master/concepticondata/conceptlists/Grierson-1928-168.tsv) seem to translate to page URLs as follows:

Concept **One (1)** lists `PAGENUMBER` `2-3` with URLs https://dsal.uchicago.edu/books/lsi/lsi.php?volume=1-2&pages=381#page/44/mode/1up and https://dsal.uchicago.edu/books/lsi/lsi.php?volume=1-2&pages=381#page/45/mode/1up in the viewer and https://dsal.uchicago.edu/books/lsi/images/lsi-v1-2-044.jpg for the raw image.

So 
> DSAL page ID = `PAGENUMBER` + 42

**Comment by xrotwang** [comment]
@PhyloStar @LinguList we can basically use TPPSR as a blueprint here, I think: See https://lsi.clld.org/parameters/2_two and https://lsi.clld.org/parameters/2_two#scans-container

**Comment by LinguList** [comment]
Yes, this is perfect! I wonder if I should also add CV patterns, as we did in TPPSR?

**Comment by PhyloStar** [comment]
Super! This looks really great. Is it possible to add the segments and IPA transcription too?

**Comment by xrotwang** [comment]
Yes, I'll flesh out the app over the next week.
